[build]
  publish = "frontend"
  command = "npm install" # Pour installer supabase-js lors du déploiement

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # Recommandé pour les dépendances NPM comme Supabase

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
